apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-fee-deployment
  labels:
    app: ms-fee-deployment
spec:
  selector:
    matchLabels:
      app: ms-fee-deployment
  replicas: 1
  template:
    metadata:
      labels:
        app: ms-fee-deployment
    spec:
      containers:
        - name: ms-fee
          image: aguzmanusc/ms-fee
          ports:
            - containerPort: 8090
          env:
            - name: SERVER_PORT
              value: "0"
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: mysql-config-map
                  key: DB_HOST_FEE
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: mysql-config-map
                  key: DB_PORT_FEE
            - name: DB_DBNAME
              valueFrom:
                configMapKeyRef:
                  name: mysql-config-map
                  key: DB_DBNAME_FEE
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: mysql-credentials
                  key: DB_USER_GENERAL
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-credentials
                  key: DB_PASSWORD_GENERAL