server:
  port: 8080
eureka:
instance:
  hostname: localhost
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
spring:
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
      discovery:
        locator:
          enabled: true
      routes:
        - id: mskart
          uri: lb://mskart
          predicates:
            - Path=/api/v1/kart/**
        - id: msfee
          uri: lb://msfee
          predicates:
            - Path=/api/v1/fees/**
        - id: msuser
          uri: lb://msuser
          predicates:
            - Path=/api/v1/usuarios/**
        - id: msreservation
          uri: lb://msreservation
          predicates:
            - Path=/api/v1/reservas/**
        - id: mspeoplediscount
          uri: lb://mspeoplediscount
          predicates:
            - Path=/api/v1/peoples/**
        - id: msfrecuencydiscount
          uri: lb://msfrecuencydiscount
          predicates:
            - Path=/api/v1/descuentos-frecuentes/**
        - id: msrack
          uri: lb://msrack
          predicates:
            - Path=/api/v1/racks/**