server:
  port: 8080
eureka:
instance:
  hostname: localhost
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: '*'
            allowedMethods: "*"
            allowedHeaders: "*"
      routes:
        - id: mskart
          uri: lb://mskart:8090
          predicates:
            - Path=/api/v1/kart/**
        - id: msfee
          uri: lb://msfee:8091
          predicates:
            - Path=/api/v1/fees/**
        - id: msuser
          uri: lb://msuser:8092
          predicates:
            - Path=/api/v1/users/**
        - id: msreservation
          uri: lb://msreservation:8093
          predicates:
            - Path=/api/v1/reservations/**